ALTER TABLE ${SCHEMA}.concept OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.concept_ancestor OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.concept_class OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.concept_relationship OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.concept_synonym OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.domain OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.drug_strength OWNER to ${SCHEMA_OWNER};
ALTER TABLE ${SCHEMA}.relationship OWNER to ${SCHEMA_OWNER};

ALTER SCHEMA ${SCHEMA} OWNER to ${SCHEMA_OWNER};
