name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main

jobs:
  image:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: vocabulon
      push_readme: README.md
      push: true
    secrets: inherit
